# docker-compose.yml
version: "3"
services:
  nodejs:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://taskmanagement:taskmanagement@localhost:5432/taskmanagement
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskmanagement
      POSTGRES_PASSWORD: taskmanagement
      POSTGRES_DB: taskmanagement
      POSTGRES_PORT: 5432

